spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/night_sail_star?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
logging:
  level:
    root: warn
    com.scxh: debug
  file:
    name: log/blog-dev.log
server:
  port: 8080