spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/night_sail_star?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    root: info
    com.scxh: debug
  file:
    name: log/blog-pro.log
server:
  port: 8081